---
language: node_js

node_js:
  - 6

sudo: false

cache:
  directories:
  - node_modules

before_install:
  - npm install -g npm@latest-2
  - npm --version

install:
  - travis_retry npm install

matrix:
  fast_finish: true

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: always
