---
language: node_js

node_js:
  - 6

sudo: false

before_install:
  - rm -rf node_modules && npm install
  - npm --version

matrix:
  fast_finish: true

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: always
